### ISSUE TITLE
Add ability to set custom release name per chart

### ISSUE THREAD

**Issue by rockholla** [Cray-HPE/loftsman#22]
#### What would you like Loftsman to do?

A manifest user should be able to set some custom release name for the chart they're installing. The release name is currently locked to the name of the chart itself without control.

#### Why is this needed?

There are use-cases for installing the same packaged chart multiple times, but with value overrides to install different resources, e.g. this is what we support today

```
spec:
  charts:
  - name: generic-service
    version: 0.1.1
    namespace: default
    values:
       name: service-web
       image: gcr.io/example/web:0.0.1
  - name: generic-service
    version: 0.1.1
    namespace: default
    values:
       name: service-api
       image: gcr.io/example/api:0.5.6
```

which would mean that the second `generic-service` just take the place of the first one in Helm release management and isn't great.

Related, we should probably do some other things to prevent release names from conflicting across different manifests. Not sure what else is left there, but I think there is something left to solve on that front.
