### ISSUE TITLE
Consider chart mirrors capabilities

### ISSUE THREAD

**Issue by rockholla** [Cray-HPE/loftsman#33]
On behalf of @zcrisler 

#### What would you like Loftsman to do?

react to the idea of chart mirrors in chart source locations

#### Why is this needed?

If we have airgapped installs, we may need to explore this

**Comment by rockholla** [comment]
@zcrisler picking up this conversation here, referencing what you put in the PR that triggered this ticket:

> I like this change a lot. It will make it very easy to locate charts in upstream repositories; however, I think it needs a "mirrors" feature similar to containerd's registry mirrors. This would enable manifests to reference a chart in it's upstream location as maintained by https://github.com/helm/chart-releaser-action (e.g., https://cray-hpe.github.io/nexus3) but provide installers the ability to resolve such requests to a local directory (i.e., to support airgap packaging). I think passing in a --mirrors configuration file to loftsman would be sufficient, although we could support a specifying individual mirrors on the command line too.

I want to talk through some examples here and see what in this is already addressed/possible, and we'll get to the meat of what improvements around this might be warranted. So, let's say you have a manifest like this:

```
apiVersion: manifests/v1beta1
metadata:
  name: master-online
spec:
  sources:
    charts:
    - type: repo
      name: nexus3
      location: https://cray-hpe.github.io/nexus3
    - type: repo
      name: victoria-metrics
      location: https://victoriametrics.github.io/helm-charts/
  charts:
  - name: nexus3
    source: nexus3
    namespace: default
    version: 1.1.0
  - name: victoria-metrics-cluster
    source: victoria-metrics
    namespace: default
    version: 0.8.24
```

And maybe that's my default, online manifest. Maybe I have tooling to generate an offline one alongside this one:

```
apiVersion: manifests/v1beta1
metadata:
  name: master-offline
spec:
  sources:
    charts:
    - type: directory
      name: nexus3
      location: /var/charts
    - type: directory
      name: victoria-metrics
      location: /var/charts
  charts:
  - name: nexus3
    source: nexus3
    namespace: default
    version: 1.1.0
  - name: victoria-metrics-cluster
    source: victoria-metrics
    namespace: default
    version: 0.8.24
```
The `spec.sources.charts` or configuration for sources is the only diff, just updated to point to a directory where packaged charts were pre-pulled or whatever.

One thing to mention here: I continue to believe that auto-generating, or assembling manifests with automated tooling is a good idea. Of course manifestgen has been used on that side to that end, but I even think that it's powerful to explore ideas like maintaining different manifests, or just sections of a manifest that can be merged together to create a master one. It's worth mentioning b/c the above means you can easily maintain multiple release manifests alongside each other as built artifacts. Think of automated pipelines being able to auto-maintain or increment chart versions for a manifest artifact when an updated chart passed integration tests, that sort of thing. Or even just a team managing the section of a manifest that they care about.

To the mirrors implementation, I'm not entirely sure the approach we'd want to take if it's needed, but taking our `master-online` manifest example above along with some of your initial ideas, maybe I'd run a ship something like:

```
loftsman ship --manifest-path ./manifest.yaml --mirrors ./mirrors.yaml
```

where `mirrors.yaml` might look something like:

```
mirrors:
- source: https://cray-hpe.github.io/nexus3
  mirror: file:///var/charts
- source: https://victoriametrics.github.io/helm-charts/
  mirror: file:///var/charts
```

A few points/concerns I have with this if I'm thinking about this right:

* I'm not sure this is any easier than simply defining something similar in the actual manifest applied, the first example presented
* I do have concerns about approaches Loftsman takes under the hood moving forward where we end up in situations where the applied manifest isn't representative of what and _how_ things were installed. [Ryan and I discussed this a bit on the last PR as I was exploring some routes to modifying the manifest on-the-fly](https://github.com/Cray-HPE/loftsman/pull/31#discussion_r621263057). We need to remain as aimed as possible on the actual manifests provided to `ship` being representative of what happens.
* I wonder if simply maintaining an http/https proxy in the environment executing the loftsman cli is also another recommended path to explore here for the need?

Let me know your thoughts and other design/implementation paths we might explore here.
