### ISSUE TITLE
Loftsman reacting incorrectly to certain remote chart index urls

### ISSUE THREAD

**Issue by rockholla** [Cray-HPE/loftsman#34]
#### What happened?

With a manifest like

```
...
spec:
  sources:
    charts:
    - type: repo
      name: chartmuseum
      location: https://chartmuseum.github.io/charts
...
charts:
- name: chartmuseum
  source: chartmuseum
  version: 3.1.0
...
```

Loftsman ends up constructing the incorrectly url for the chart:

```
Error: failed to download "https://chartmuseum.github.io/charts/https:/github.com/chartmuseum/charts/releases/download/chartmuseum-3.1.0/chartmuseum-3.1.0.tgz"
```

We detect whether or not the root helm repo url is included in the chart index record and respond correctly, but in the case of it being a pointer to a totally different place, this is what happens.

#### What did you expect to happen?

For the correct URL to be found for pulling the chart

#### How to reproduce the issue (as minimally and precisely as possible):

Using a manifest like the above and running a ship

#### Anything else worth sharing:

N/A
