### ISSUE TITLE
Verify chart signatures before deploy

### ISSUE THREAD

**Issue by zcrisler** [Cray-HPE/loftsman#37]
#### What would you like Loftsman to do?

Verify available chart signatures during install and upgrade, see https://helm.sh/docs/topics/provenance/.

#### Why is this needed?

To verify the integrity and origin of a chart package.

**Comment by rockholla** [comment]
I've moved this into the next minor release milestone, which I'm shooting to get out in the next few weeks.

Initial design idea for this would be a manifest that looks something like this:

```
apiVersion: manifests/v1beta1
metadata:
  name: example
spec:
  sources:
    charts:
    - type: directory
      name: local
      location: ./charts
    - type: repo
      name: repo1
      location: https://repo1.my.org
    - type: repo
      name: repo2
      location: https://repo2.my.org
  all:
    verify: true # would use the default keyring path (~/.gnupg/pubring.gpg) for any chart that doesn't specify explicitly
  charts:
  - name: chart1
    source: local
    namespace: default
    version: 0.1.0
  - name: chart2
    source: repo1
    namespace: default
    releaseName: chart2
    version: 0.0.1
    verify: false # would override to not use the global verify to do the install/upgrade
  - name: chart3
    source: repo2
    namespace: default
    version: 3.0.0
    keyringPath: /var/repo2-keyring.gpg # rather than the default system keyring, could use an alternate
```

Let me know if you have any input on that tentative design @zcrisler. Thanks.
